services:
  - type: web
    name: rawby-server
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: rawby-data
      mountPath: /app/data
      sizeGB: 1
