// ============================================================
// RAWBY — curated shooting spots. Hungary-first (that's where
// the filmmakers are right now): ~140 videography-oriented
// locations across the whole country — hidden gems, urbex,
// lookouts, waterfalls, ghost villages, pusztas, castles.
// Compiled from travel/photo research (Culture Trip, Our
// Wanders, szallas.hu, Turista Magazin, Locationscout, Aktív
// Kalandor) + local knowledge. Coordinates are approximate —
// good for a map pin, not for navigation.
// World packs come as the community grows; community spots
// from the server render alongside these on the Atlas.
// ============================================================
import type { Spot } from "../types";

const s = (id: string, name: string, lat: number, lng: number, note: string): Spot => ({
  id: `hu-${id}`,
  curated: true,
  name,
  lat,
  lng,
  note,
});

export const CURATED_SPOTS: Spot[] = [
  // ── Budapest ──────────────────────────────────────────────
  s("parliament", "Parliament from Bem rakpart", 47.505, 19.045, "Golden hour across the Danube — the classic wide. Blue hour doubles the lights in the water."),
  s("bastion", "Fisherman's Bastion", 47.502, 19.034, "Arches frame the city. Sunrise = empty terraces, warm side light."),
  s("chain-bridge", "Chain Bridge lion terrace", 47.499, 19.043, "Low angle through the chains at night; car light-trails for free production value."),
  s("gellert", "Gellért Hill lookout", 47.484, 19.046, "Highest city panorama. Autumn fog mornings are cinema."),
  s("citadella", "Citadella walls", 47.487, 19.043, "Brutal stone walls + the Liberty Statue silhouette at dusk."),
  s("ruin-bars", "Szimpla Kert / ruin bar district", 47.497, 19.063, "Texture heaven — neon, decay, fairy lights. Ask before filming inside."),
  s("keleti", "Keleti station hall", 47.5, 19.083, "Iron-and-glass cathedral light at midday. Arrival/departure beats."),
  s("margit", "Margaret Island water tower", 47.527, 19.049, "Green tunnel paths, dawn runners, the old tower — quiet-story backlot."),
  s("m4-metro", "M4 metro (Szent Gellért tér)", 47.482, 19.052, "Brutalist concrete + light wells. Handheld tolerated; tripods need a permit."),
  s("vajdahunyad", "Vajdahunyad Castle", 47.515, 19.081, "Fairy-tale castle over the boating lake; skaters in winter, mist in October."),
  s("hosok", "Heroes' Square at dawn", 47.515, 19.078, "Empty at 6am — wide symmetrical frames, skaters and pigeons for motion."),
  s("szechenyi", "Széchenyi Baths outdoor pools", 47.518, 19.082, "Steam over yellow baroque in winter — book a filming slot, or shoot from the colonnade."),
  s("gul-baba", "Gül Baba's tomb, Rózsadomb", 47.517, 19.035, "Ottoman türbe + rose garden with a rooftop view — soft story corner above the city."),
  s("parisi", "Párisi Udvar arcade", 47.493, 19.054, "Gold mosaic arcade light — 1900s texture for interiors."),
  s("nyc-cafe", "New York Café exterior", 47.498, 19.07, "The 'most beautiful café' — shoot the gilded corner from the tram island."),
  s("szabadsag-hid", "Liberty Bridge green steel", 47.486, 19.055, "Climbable-looking green truss (stay off it) — cyclists at sunset, tram crossings."),
  s("kopaszi", "Kopaszi-gát bay", 47.464, 19.058, "Calm bay, modern towers behind — clean minimal water frames."),
  s("normafa", "Normafa meadow", 47.507, 18.96, "City-edge meadow above the fog line; winter sleds, spring picnics."),
  s("janos-hegy", "Erzsébet lookout, János Hill", 47.518, 18.959, "White stone tower over the whole basin — arrive by chairlift for a moving shot."),
  s("zugliget", "Zugliget chairlift", 47.515, 18.973, "Slow aerial-style tracking shots over the forest for the price of a ticket."),
  s("romai", "Római-part floating bars", 47.573, 19.05, "Plane trees, gravel, river bars — a summer-evening world of its own."),
  s("lupa", "Lupa Lake beach", 47.605, 19.06, "Turquoise quarry lake with white sand — 'Maldives' frames 20 min from town."),
  s("aquincum", "Aquincum Roman ruins", 47.564, 19.049, "Roman grid + column stumps — long-lens compression at low sun."),
  s("nepliget", "Népliget brutalist planetarium", 47.478, 19.098, "Decaying socialist-modern dome in a shaggy park — moody urbex-lite."),
  s("budafok", "Budafok cellar town", 47.428, 19.038, "Wine-cellar streets carved into limestone — lantern-lit walking shots."),

  // ── Danube Bend + Börzsöny ────────────────────────────────
  s("visegrad", "Visegrád Citadel", 47.785, 18.971, "The Danube Bend wide — best 1h before sunset when the river goes bronze."),
  s("predikaloszek", "Prédikálószék cliff", 47.766, 18.94, "Airy cliff platform straight over the Bend — Hungary's most drone-worthy view (check NP rules)."),
  s("ram-szakadek", "Rám gorge scramble", 47.76, 18.9, "Ladders + waterfall chutes in a narrow gorge — action-cam territory after rain."),
  s("zebegeny", "Zebegény river curve", 47.795, 18.905, "The S-curve village with a Ştefan church tower — shoot from the Kálvária hill."),
  s("nagymaros", "Nagymaros bank facing the castle", 47.79, 18.955, "Ferry crossings with the citadel hill behind — commuter-romance frames."),
  s("kiralyret", "Királyrét forest railway", 47.83, 18.975, "Tiny green forest train — track-side pans, steam in cold air."),
  s("csovanyos", "Csóványos summit tower", 47.87, 18.94, "Börzsöny's highest lookout — cloud inversions at dawn."),
  s("vac", "Vác baroque riverfront", 47.775, 19.13, "Pastel baroque row reflected in the Danube — quieter than Szentendre."),
  s("esztergom", "Esztergom Basilica from the Bend", 47.799, 18.737, "The dome over the river — shoot from the Slovak bank for the full postcard."),
  s("szentendre", "Szentendre riverside lanes", 47.668, 19.076, "Mediterranean-feeling alleys 40 min from Pest. Painters' light all day."),

  // ── Balaton + Bakony ──────────────────────────────────────
  s("tihany", "Tihany Abbey", 46.914, 17.888, "Twin towers over the lake; lavender rows bloom mid-June."),
  s("badacsony", "Badacsony basalt hill", 46.79, 17.494, "Vineyard slopes + volcanic ridges above Balaton. Harvest fog is unreal."),
  s("szigliget", "Szigliget castle hill", 46.8, 17.437, "Ruined walls over reed marshes — 360° of lake and volcano cones."),
  s("hegyestu", "Hegyestű basalt organ pipes", 46.94, 17.59, "Sliced volcano — vertical basalt columns like a stone pipe organ. Harsh light works here."),
  s("szentbekalla", "Szentbékkálla stone sea", 46.9, 17.56, "Giant sandstone boulders in a meadow — climbable foregrounds, Káli-basin light."),
  s("szent-gyorgy", "Szent György-hegy basalt cliffs", 46.83, 17.44, "Basalt curtains + old press houses; the most cinematic of the witness hills."),
  s("csobanc", "Csobánc castle ruin", 46.87, 17.5, "Lonely hilltop ruin — silhouette shots against lake haze."),
  s("salfold", "Salföld monastery ruin", 46.83, 17.55, "Pálos ruin hidden in woods — soft light, zero crowds."),
  s("tapolca", "Tapolca cave lake", 46.883, 17.441, "Rowing through a lit limestone cave — natural dolly shots."),
  s("heviz", "Hévíz thermal lake", 46.79, 17.19, "Steam + water lilies on the world's largest swimmable thermal lake. Winter mornings = fog machine."),
  s("keszthely", "Festetics Palace, Keszthely", 46.768, 17.242, "Baroque palace + mirror pond; symmetrical establishing shots."),
  s("fonyod", "Fonyód high bank", 46.75, 17.59, "The postcard ACROSS the lake at the volcano cones — best at sunset."),
  s("boglar", "Balatonboglár sphere lookout", 46.77, 17.66, "Retro-futurist sphere tower — geometric frames + lake panorama."),
  s("zamardi", "Zamárdi high bank", 46.88, 17.95, "Sweeping south-shore vista; paragliders launch here in the right wind."),
  s("fured", "Balatonfüred Tagore promenade", 46.953, 17.889, "Old-money lakeside — sailboat masts, plane trees, evening lamps."),
  s("akarattya", "Balatonakarattya loess cliff", 47.02, 18.15, "Crumbling high shore with lone trees over the water."),
  s("somlo", "Somló hill vineyards", 47.14, 17.37, "A lone volcano of vines with a tiny castle stub — inversion fog island in autumn."),
  s("hubertlaki", "Hubertlaki 'sunken forest' lake", 47.25, 17.73, "Dead trunks standing in still water — Hungary's ghost lake. Polariser + dawn mist."),
  s("cuha", "Cuha valley railway", 47.32, 17.79, "Old rail line threading a wooded gorge — shoot the viaducts and tunnels."),
  s("csesznek", "Csesznek castle", 47.35, 17.88, "Ruin perched on a crag over the road bend — headlight trails at dusk."),
  s("zirc", "Zirc abbey + arboretum", 47.26, 17.87, "White cistercian towers + ancient trees; quiet interior light."),
  s("veszprem", "Veszprém viaduct + castle row", 47.093, 17.9, "Art-deco viaduct + the one-street castle hill — two locations in one town."),
  s("szentkiraly", "Szentkirályszabadja ghost garrison", 47.07, 17.97, "'Little Moscow' — abandoned Soviet base blocks. Hungary's Chernobyl look; enter at your own risk."),
  s("balatonederics", "Balatonederics abandoned mansion", 46.79, 17.37, "The infamous derelict castle — horror-story texture (exterior only)."),

  // ── Northern hills: Bükk · Mátra · Zemplén · Aggtelek ─────
  s("lillafured", "Lillafüred palace + waterfall", 48.102, 20.62, "Neo-renaissance palace, hanging gardens, Hungary's tallest waterfall next door."),
  s("hamori", "Lake Hámori rowboats", 48.09, 20.61, "Palace reflections from a rented rowboat — floating tripod included."),
  s("szalajka", "Szalajka valley + Fátyol falls", 48.05, 20.43, "Veil-waterfall over limestone steps; trout streams + forest rail."),
  s("belapatfalva", "Bélapátfalva abbey", 48.06, 20.36, "Romanesque abbey alone under the Bél-kő cliff — monastic minimalism."),
  s("belko", "Bél-kő quarry ridge", 48.07, 20.34, "Terraced white quarry mountain — brutal geometric backdrops."),
  s("nagymezo", "Bükk plateau, Nagymező", 48.07, 20.5, "High karst meadow with sinkholes — star-lapse country (official dark-sky park)."),
  s("haromko", "Három-kő cliff lookout", 48.08, 20.47, "Cliff-edge view over endless forested hills — layered ridgeline shots at dusk."),
  s("diosgyor", "Diósgyőr castle", 48.09, 20.69, "Restored gothic courtyard — torch-lit medieval frames."),
  s("rudabanya", "Rudabánya rust-red pit lake", 48.38, 20.63, "Iron-mine lake in impossible colours — Mars meets Iceland."),
  s("aggtelek", "Baradla cave, Aggtelek", 48.47, 20.5, "25 km UNESCO cave — cathedral chambers, concert hall lighting."),
  s("derenk", "Derenk ghost village", 48.52, 20.6, "Razed village on a karst meadow — a chapel, cellar holes, silence."),
  s("tengerszem", "Megyer-hegy tarn (mine pool)", 48.35, 21.55, "Millstone quarry turned emerald pool ringed by cliffs — Hungary's #1 'is this real' spot."),
  s("sarospatak", "Sárospatak Rákóczi castle", 48.32, 21.57, "Renaissance loggia + Bodrog riverbank willows."),
  s("fuzer", "Füzér castle in the sky", 48.55, 21.45, "Chapel-castle on a volcanic cone — cloud seas below it in autumn dawns."),
  s("boldogko", "Boldogkő castle ridge", 48.34, 21.23, "Castle on a knife-edge rock over vine rows — golden hour from the east."),
  s("regec", "Regéc castle ruin", 48.39, 21.35, "Wilder, emptier Zemplén ruin — hike-in earns lonely wides."),
  s("tokaj", "Tokaj vineyards", 48.123, 21.41, "Terraced wine hills over the Bodrog; October colours are unreal."),
  s("kekesteto", "Kékestető TV tower", 47.87, 20.01, "Hungary's highest point — above the winter fog, ski-run foregrounds."),
  s("galyateto", "Galyatető stone lookout", 47.92, 19.91, "Round stone tower over pine forest — snow scenes without the Alps."),
  s("sasto", "Sástó lake + tower", 47.83, 19.97, "Reedy lake, rusty lookout, paddle boats — retro summer palette."),
  s("sirok", "Sirok castle rocks", 47.93, 20.19, "Castle carved INTO the rock spires — fantasy-genre skyline."),
  s("recsk", "Recsk quarry memorial", 47.93, 20.07, "The 'Hungarian Gulag' quarry — heavy history, heavier atmosphere. Treat with respect."),
  s("noszvaj", "Noszvaj cave dwellings", 47.94, 20.47, "Hobbit-like carved cave homes in a tuff cliff — artists still live here."),
  s("egerszalok", "Egerszalók salt hill", 47.86, 20.34, "White travertine terraces steaming under thermal water — Pamukkale in miniature."),
  s("eger", "Eger castle + minaret", 47.906, 20.377, "Baroque streets and castle walls; warm stone at sunset."),
  s("szomolya", "Szomolya beehive stones", 47.89, 20.49, "Mysterious carved niches in tuff cones — nobody knows who made them."),
  s("hollóko", "Hollókő old village", 47.995, 19.593, "UNESCO Palóc village — whitewashed walls, period texture without a set budget."),
  s("salgo", "Salgó castle basalt", 48.14, 19.85, "Basalt-top ruin — Slovak hills layer into the distance."),
  s("somosko", "Somoskő basalt falls", 48.17, 19.85, "Frozen 'basalt waterfall' columns under a border castle."),
  s("ipolytarnoc", "Ipolytarnóc fossil trail", 48.23, 19.63, "Petrified miocene beach — 20-million-year-old footprints under a canopy walk."),

  // ── Great Plain: Hortobágy · Tisza-tó · Kiskunság · Szatmár ─
  s("hortobagy", "Hortobágy Nine-hole Bridge", 47.582, 21.152, "Big-sky steppe — mirages in summer, grey cattle herds, the arched bridge."),
  s("poroszlo", "Tisza-tó ecocentre + lily lagoons", 47.65, 20.66, "Boardwalks over waterlily fields; giant aquarium interiors as B-roll."),
  s("sarud", "Sarud water-maze kayak trail", 47.6, 20.6, "Paddle-through flooded forest channels — jungle frames in central Europe."),
  s("tiszafured", "Tiszafüred lily bays", 47.62, 20.76, "July = thousands of white waterlilies; shoot from a canoe at sunrise."),
  s("debrecen-nagyerdo", "Debrecen Nagyerdő park bath", 47.55, 21.62, "Forest park + art-deco water tower turned lookout bar."),
  s("debrecen", "Debrecen Great Church", 47.53, 21.63, "Yellow twin-tower calvinist icon — symmetry + market square life."),
  s("sosto", "Sóstó open-air village museum", 48.0, 21.72, "Full skanzen of old-Hungary streets — period sets ready to roll."),
  s("szeged", "Szeged Dóm + Tisza bank", 46.25, 20.15, "Twin brick towers + the slow Tisza; Europe's beloved secondary-city light."),
  s("algyo", "Algyő painters' Tisza bank", 46.33, 20.21, "Willow-lined riverbank + buffalo reserve nearby — a painters' colony for a reason."),
  s("opusztaszer", "Ópusztaszer heritage park", 46.49, 20.08, "The Feszty panorama + reconstructed farmsteads — instant 1800s."),
  s("csaj-to", "Csaj-tó bird lakes", 46.56, 20.05, "One of central Europe's great bird stopovers — crane clouds at dusk (Oct-Nov)."),
  s("bugac", "Bugac puszta + herders", 46.69, 19.63, "Grey cattle, rackas, csikós horse shows, lone sweep wells (gémeskút) — the mythic Alföld."),
  s("fulopszallas", "Fülöpháza shifting sand dunes", 46.87, 19.42, "Real sand dunes with juniper — desert doubles an hour from Budapest."),
  s("kolon", "Kolon-tó reed world", 46.77, 19.33, "Endless reed beds + boardwalk — winter frost turns it silver."),
  s("szelidi", "Szelidi soda lake", 46.57, 19.06, "Milky-white szik water + pink dawns — the Alföld's alien lakes."),
  s("kecskemet", "Kecskemét ornamented palace", 46.906, 19.69, "Art-nouveau Cifrapalota — ceramic flowers on undulating walls."),
  s("gyula", "Gyula brick castle", 46.64, 21.28, "Central Europe's rare intact brick gothic castle + bath steam next door."),
  s("szarvas", "Szarvas arboretum + dead-Körös", 46.87, 20.53, "Riverside arboretum — autumn reflections in the oxbow."),
  s("mezohegyes", "Mezőhegyes imperial stud farm", 46.31, 20.82, "Monarchy-era horse barns in formation — Wes Anderson symmetry."),
  s("turistvandi", "Túristvándi water mill", 48.05, 22.64, "Working wooden water mill on the Túr — plum-country storybook."),
  s("oreg-tur", "Öreg-Túr backwaters", 48.03, 22.55, "Slow tea-coloured river tunnels under willows — canoe tracking shots."),
  s("csaroda", "Csaroda painted church", 48.16, 22.46, "13th-c church with 'smiling saints' frescoes — tiny, ancient, moving."),
  s("takos", "Tákos 'barefoot Notre-Dame'", 48.18, 22.42, "Wattle-and-daub protestant church, painted coffered ceiling — folk-art jewel."),
  s("szabolcs", "Szabolcs earthen fortress", 48.17, 21.5, "Grass-covered 1000-year-old earth ramparts over the Tisza."),

  // ── South Transdanubia: Mecsek · Villány · Drava ──────────
  s("pecs", "Pécs — Zsolnay quarter", 46.073, 18.238, "Ceramic-tiled facades + industrial-romantic courtyards in the south's warmest light."),
  s("misina", "Misina TV tower, Mecsek", 46.1, 18.21, "Concrete needle over the city — panoramic café level for timelapses."),
  s("tettye", "Tettye ruins terrace", 46.09, 18.23, "16th-c monastery ruin on a limestone terrace over Pécs rooftops."),
  s("orfu", "Orfű lakes", 46.15, 18.15, "Chain of four lakes in green hills — misty dawn SUP shots."),
  s("abaliget", "Abaliget cave + lake", 46.14, 18.12, "Dripstone cave with an underground stream and a quiet lake outside."),
  s("villany", "Villány cellar row", 45.87, 18.45, "White gable cellars in a row — wine-country establishing shots."),
  s("palkonya", "Palkonya painted village", 45.9, 18.4, "Circle of listed cellars + a round-arch church — protected village charm."),
  s("siklos", "Siklós castle", 45.85, 18.3, "Intact medieval castle — walkable walls, gothic chapel light."),
  s("nagyharsany", "Nagyharsány sculpture quarry", 45.86, 18.42, "Open-air statue park inside a white quarry bowl under Szársomlyó peak."),
  s("mohacs", "Mohács Busó riverbank", 45.99, 18.68, "Danube bank of the Busójárás — in carnival week it's a horror-folk documentary."),
  s("gemenc", "Gemenc flooded forest", 46.2, 18.8, "Danube floodplain jungle — deer, oxbows, a narrow-gauge rail through it."),
  s("baja", "Baja Sugovica sunset", 46.18, 18.95, "Fish-soup town where the sun sets INTO the river — reliable postcard."),
  s("zselic", "Zselic starry-sky park", 46.23, 17.85, "Certified dark-sky reserve — Milky Way timelapses + a canopy lookout tower."),
  s("dravatamasi", "Drava riverbank", 45.96, 17.46, "Wild border river — gravel bars, kingfishers, no crowds ever."),
  s("szekszard", "Szekszárd vineyard amphitheatre", 46.35, 18.7, "Vines on steep loess ridges — long-shadow rows at sunset."),

  // ── West + North Transdanubia: Őrség · Sopron · Vértes ────
  s("sopron", "Sopron Fire Tower old town", 47.69, 16.59, "Intact medieval core — shoot down Új utca's arc at blue hour."),
  s("fertorakos", "Fertőrákos quarry theatre", 47.72, 16.65, "Roman-cut limestone halls — colossal pillars, cave-theatre acoustics."),
  s("ferto", "Fertő lake stilt houses", 47.68, 16.71, "Reed-world with wooden stilt cottages — Hungarian 'sea of grass'."),
  s("fertod", "Esterházy Palace, Fertőd", 47.62, 16.87, "The 'Hungarian Versailles' — courtyard symmetry + French garden."),
  s("koszeg", "Kőszeg old town", 47.39, 16.54, "Painted-facade square below the Alps' first hills — Grand Budapest vibes."),
  s("irottko", "Írott-kő lookout", 47.35, 16.43, "Border-straddling tower on the Alps' last peak — two countries in one frame."),
  s("jak", "Ják abbey portal", 47.14, 16.58, "Hungary's finest Romanesque doorway — carved saints in raking light."),
  s("pityerszer", "Őrség — Pityerszer hamlet", 46.87, 16.4, "Wooden farmhouses on grassy 'szer' clusters — pumpkin-seed-oil country."),
  s("velemer", "Velemér light-church", 46.74, 16.38, "13th-c church built so sunbeams hit specific frescoes on calendar days — light IS the story."),
  s("magyarszombatfa", "Magyarszombatfa potters", 46.78, 16.4, "Working folk pottery village — hands-and-clay macro heaven."),
  s("kis-balaton", "Kis-Balaton, Kányavári island", 46.64, 17.15, "Wooden arc bridge into a bird world — egrets at dawn."),
  s("zalaszanto", "Zalaszántó stupa", 46.89, 17.14, "A white Buddhist stupa over Hungarian hills — the frame nobody expects."),
  s("sumeg", "Sümeg castle hill", 46.98, 17.28, "Whole-hill fortress — jousting shows for period action B-roll."),
  s("sag-hegy", "Ság-hegy crater rim", 47.23, 17.1, "Half-mined volcano leaving a crater amphitheatre — vineyard moonscape."),
  s("pannonhalma", "Pannonhalma Archabbey", 47.55, 17.76, "Thousand-year monastery over lavender fields (late June) — drone-free zone, long lens from the road."),
  s("szigetkoz", "Szigetköz water world", 47.85, 17.4, "Braided Danube side-arms — gravel islands, kayak channels, morning vapour."),
  s("gyor", "Győr baroque riverbanks", 47.69, 17.63, "Three rivers meet under pastel baroque — balconied corner houses."),
  s("tata", "Tata Old Lake + castle", 47.65, 18.32, "Lakeside castle + November wild-goose migrations — thousands lift off at dawn."),
  s("bokod", "Bokod floating village", 47.49, 18.26, "Stilt cottages + boardwalks on a power-plant lake — THE Hungarian photo icon in fog."),
  s("szelim", "Szelim cave + Turul, Tatabánya", 47.59, 18.39, "Huge cave mouth framing the valley + Europe's largest bird statue above."),
  s("gant", "Gánt bauxite 'Mars' pit", 47.39, 18.39, "Blood-red bauxite badlands — Mars scenes, zero CGI. Harsh midday sun actually helps."),
  s("csokako", "Csókakő castle terrace", 47.35, 18.27, "Small ruin, huge view over the Zámolyi basin — paraglider launches beside it."),
  s("zsambek", "Zsámbék church ruin", 47.55, 18.72, "Half-collapsed Romanesque towers alone against the sky — Hungary's most cinematic ruin."),
  s("bory", "Bory Castle, Székesfehérvár", 47.2, 18.44, "A castle one man built by hand over 40 years for his wife — a love story with towers."),
  s("etyek", "Etyek wine hills + studios", 47.45, 18.75, "Press-house rows next to Korda film studios — wine country that IS a backlot."),
  s("velence", "Lake Velence bird reserve", 47.19, 18.6, "Reed islands + herons 40 min from the city — beginner-friendly wildlife hides."),
];
